// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoadingIndicatorController from "./loading_indicator_controller" // 修正箇所
application.register("loading-indicator", LoadingIndicatorController) // 変更した名前で登録
